# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-webmain-prod-uksouth

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://crazdevprod.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_73e189a03ff3478daef6b837ac0b1275 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a7ed18cd51894f0eb5d468b40db499cf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: crazdevprod.azurecr.io/azdev-space-ui:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-webmain-prod-uksouth'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_21ef310cb74346b4a06a4752e193acc3 }}
        images: 'crazdevprod.azurecr.io/azdev-space-ui:${{ github.sha }}'
